
title: Eco Rewards
email: linusnorton@gmail.com
description: >-
  Rewarding Green Travel Choices
url: "https://www.ecorewards.co.uk/"
baseurl: ""
lang: "en"
plugins:
  - jekyll-minifier
  - jekyll-redirect-from
exclude:
  - README.md
  - vendor/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .git/
permalink: /bracknell/:title
excerpt_separator: <!--more-->
sass:
  style: compressed
collections:
  orgs:
    output: true
