
title: Eco Rewards
email: linusnorton@gmail.com
description: >-
  Reward green travel choices
baseurl: "ecorewards.co.uk/"
url: "https://www.ecorewards.co.uk/"
lang: "en"
plugins:
  - jekyll-minifier
exclude:
  - README.md
  - vendor/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .git/
permalink: /posts/:title
excerpt_separator: <!--more-->
sass:
  style: compressed
